// PayFast Button Integration - Using Generated PayFast Form Code
// This matches the exact form structure generated by PayFast dashboard

export const submitPayFastDonation = (donationData) => {
  const amount = parseFloat(donationData.amount).toFixed(2);
  
  // PayFast form data based on the generated code
  const payFastFormData = {
    cmd: "_paynow",
    receiver: "30921435", // Your PayFast receiver ID from the generated form
    return_url: "https://www.youngeagles.org.za/donation-success",
    cancel_url: "https://www.youngeagles.org.za/donation-cancelled", 
    notify_url: "https://www.youngeagles.org.za/api/payfast-webhook",
    amount: amount,
    custom_quantity: "1",
    item_name: "Young Eagles Digital Future Donation",
    item_description: "Donation to support digital education initiatives at Young Eagles Home Care Centre - helping children access technology, robotics, and modern learning tools.",
    
    // Shipping address - using donor information
    line1: donationData.company || "Individual Donation",
    line2: "",
    city: "Johannesburg", // Default city
    region: "Gauteng", // Default province
    country: "South Africa",
    code: "2000", // Default postal code
    
    // Custom fields for tracking
    m_payment_id: donationData.reference_number,
    custom_str1: donationData.full_name,
    custom_str2: donationData.contact_number,
    custom_str3: donationData.email,
  };

  console.log('🚀 PayFast Form Data:', payFastFormData);

  // Create and submit the form dynamically
  const form = document.createElement("form");
  form.name = "PayFastPayNowForm";
  form.method = "POST";
  form.action = "https://payment.payfast.io/eng/process"; // Using the exact URL from generated code
  
  // Add all form fields as hidden inputs
  Object.entries(payFastFormData).forEach(([key, value]) => {
    if (value !== null && value !== undefined && value !== "") {
      const input = document.createElement("input");
      input.type = "hidden";
      input.name = key;
      input.value = value.toString();
      form.appendChild(input);
    }
  });

  // Add the form to the page temporarily and submit
  document.body.appendChild(form);
  
  console.log('📤 Submitting PayFast form...');
  form.submit();
  
  // Clean up
  document.body.removeChild(form);
};

// JavaScript functions from PayFast generated code
export const customQuantitiesPayFast = (formReference) => {
  formReference['amount'].value = formReference['amount'].value * formReference['custom_quantity'].value;
  return true;
};

export const actionPayFastJavascript = (formReference) => {
  let shippingValidOrOff = typeof window.shippingValid !== 'undefined' ? window.shippingValid : true; 
  let customValid = shippingValidOrOff ? customQuantitiesPayFast(formReference) : false;
  
  if (typeof window.shippingValid !== 'undefined' && !window.shippingValid) {
    return false;
  }
  if (typeof customValid !== 'undefined' && !customValid) {
    return false;
  }
  return true;
};
